"use client";

import React, { useEffect, useRef, useState } from 'react';
import BpmnViewer from 'bpmn-js/lib/NavigatedViewer';

// Import BPMN-JS styles
import 'bpmn-js/dist/assets/diagram-js.css';
import 'bpmn-js/dist/assets/bpmn-font/css/bpmn-embedded.css';

const BPMNViewer = ({ xml, id = 'bpmn-viewer' }) => {
    const containerRef = useRef(null);
    const viewerRef = useRef(null);
    const [error, setError] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        if (!containerRef.current) return;

        // Initialize viewer if not already initialized
        if (!viewerRef.current) {
            viewerRef.current = new BpmnViewer({
                container: containerRef.current,
                width: '100%',
                height: '100%'
            });
        }

        const renderBPMN = async () => {
            try {
                setLoading(true);
                setError(null);

                if (!xml) {
                    setError('No BPMN XML provided');
                    setLoading(false);
                    return;
                }

                // Check if xml is valid XML (basic check)
                if (!xml.includes('<?xml') && !xml.includes('<bpmn:')) {
                    setError('Invalid BPMN XML format provided.');
                    setLoading(false);
                    return;
                }

                await viewerRef.current.importXML(xml);

                // Fit to viewport
                const canvas = viewerRef.current.get('canvas');
                canvas.zoom('fit-viewport');

            } catch (err) {
                console.error('BPMN Render Error:', err);
                setError('Failed to render BPMN diagram. The XML may be invalid or incorrectly generated by AI.');
            } finally {
                setLoading(false);
            }
        };

        renderBPMN();

        return () => {
            // Cleanup on unmount - although BpmnViewer doesn't have a formal destroy() usually,
            // we could clear the container if needed.
        };
    }, [xml]);

    if (error) {
        return (
            <div className="bg-red-50 text-red-600 p-6 rounded-xl border border-red-100 flex flex-col items-center max-w-md text-center mx-auto my-4">
                <span className="mb-2 font-bold uppercase tracking-wider text-[10px]">Render Error</span>
                <p className="text-sm font-medium">{error}</p>
                <details className="mt-4 w-full">
                    <summary className="text-[10px] cursor-pointer hover:underline text-gray-400">View source XML</summary>
                    <pre className="mt-2 p-3 bg-white text-gray-400 text-[10px] rounded-lg w-full text-left overflow-auto max-h-[150px] font-mono border border-gray-100">
                        {xml}
                    </pre>
                </details>
            </div>
        );
    }

    return (
        <div className="bpmn-viewer-container relative w-full h-[500px] bg-white rounded-xl border border-gray-100 overflow-hidden shadow-sm">
            {loading && (
                <div className="absolute inset-0 flex items-center justify-center bg-white/80 z-10">
                    <div className="flex flex-col items-center gap-2">
                        <div className="w-8 h-8 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin"></div>
                        <span className="text-xs font-medium text-gray-500">Rendering BPMN Process...</span>
                    </div>
                </div>
            )}
            <div ref={containerRef} className="w-full h-full" id={id} />

            {/* Custom styles to hide the BPMN.io logo and refine the layout */}
            <style jsx global>{`
                .bjs-powered-by {
                    display: none !important;
                }
            `}</style>

            {/* Legend or Controls Info - Moved to bottom-left to avoid any default viewer overlays */}
            <div className="absolute bottom-4 left-4 bg-white/80 backdrop-blur-sm p-2 rounded-lg border border-gray-200 text-[10px] text-gray-500 shadow-sm pointer-events-none z-20">
                Scroll to zoom • Click and drag to pan
            </div>
        </div>
    );
};

export default BPMNViewer;
